[package]
authors = ["Splinter Suidman (splintah)", "Sybrand Aarnoutse (syberant)"]
name = "game-of-life"
version = "0.3.0"

[[bin]]
name = "gol-win"
path = "./src/window/mod.rs"

[[bin]]
name = "gol-cli"
path = "./src/cli.rs"

[lib]
name = "game_of_life"
path = "./src/lib/mod.rs"

[features]
# This feature is only used for benchmarks since the test crate is unstable.
bench = []

[dependencies]
piston_window = "0.77"
rand = "0.4"
terminal_size = "0.1.7"
rayon = "1.0"
clap = "~2.31.0"
